name: CI

on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu cần
  pull_request:
    branches:
      - main  # Thay đổi tên nhánh nếu cần

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Thay đổi phiên bản Node.js nếu cần

      - name: Install dependencies
        run: npm install  # Hoặc lệnh cài đặt tương ứng với ngôn ngữ bạn đang sử dụng

      - name: Run tests
        run: npm test  # Hoặc lệnh chạy test tương ứng
